_slips/slip-21/3/SimplePoll/PollApp/urls.py
from django.urls import path

from . import views

app_name = "PollApp"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("poll/<int:poll_id>/", views.PollView.as_view(), name="poll"),
]

_slips/slip-21/3/SimplePoll/SimplePoll/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("PollApp.urls")),
]

_slips/slip-21/3/SimplePoll/PollApp/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Choice(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Poll(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    choices = models.ManyToManyField(
        Choice, related_name='related_polls', blank=True)

    def __str__(self):
        return self.name


class Vote(models.Model):
    poll = models.ForeignKey(
        Poll, on_delete=models.SET_NULL, related_name="votes", null=True, blank=True)
    choice = models.ForeignKey(
        Choice, on_delete=models.SET_NULL, related_name="votes", null=True, blank=True)
    timestamp = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return f"{self.poll.name} - {self.choice.name}"

_slips/slip-21/3/SimplePoll/PollApp/views.py
from django.shortcuts import render
from django.views import View

from PollApp.models import Choice, Poll, Vote

# Create your views here.


class HomeView(View):

    def get(self, request):
        polls = Poll.objects.all()
        return render(
            request,
            template_name="PollApp/home.html",
            context={
                "polls": polls,
            }
        )


class PollView(View):

    def get(self, request, poll_id):
        poll = Poll.objects.get(id=poll_id)
        return render(
            request,
            template_name="PollApp/poll.html",
            context={
                "poll": poll,
            }
        )

    def post(self, request, poll_id):
        requestData = request.POST

        choice_id = requestData.get('choice_id')

        poll = Poll.objects.get(id=poll_id)
        choice = Choice.objects.get(id=choice_id)
        Vote.objects.create(
            poll=poll,
            choice=choice,
        )

        poll_results = []
        for choice in poll.choices.all():
            voteCount = Vote.objects.filter(poll=poll, choice=choice).count()
            poll_results.append([choice.name, voteCount])

        return render(
            request,
            template_name="PollApp/poll.html",
            context={
                "poll": poll,
                "success_message": "Voted Successfully",
                "poll_results": poll_results,
            }
        )

_slips/slip-21/3/SimplePoll/PollApp/templates/PollApp/home.html
{% extends 'base.html' %}

{% block body %}

{% for poll in polls %}
<div class="card">
  <div class="card-body">
    <h5 class="card-title">{{ poll.name }}</h5>
    <p class="card-text">{{ poll.description }}</p>
    <a href="{% url 'PollApp:poll' poll.id %}" class="btn btn-primary">Vote</a>
  </div>
</div>
{% endfor %}

{% endblock %}

_slips/slip-21/3/SimplePoll/PollApp/templates/PollApp/poll.html
{% extends 'base.html' %}

{% block body %}

{% if success_message %}
<div class="alert alert-success"> {{ success_message }} </div>
{% endif %}

<h2> {{ poll.name }} </h2>
<i>
  <h6> {{ poll.description }} </h6>
</i>
<hr class="my-4">
<form method="post">
  {% csrf_token %}
  {% for choice in poll.choices.all %}
  <div class="form-check">
    <input class="form-check-input" type="radio" name="choice_id" id="{{ choice.id }}" value="{{ choice.id }}">
    <label class="form-check-label" for="{{ choice.id }}">
      {{ choice.name }}
    </label>
  </div>
  {% endfor %}
  <hr class="my-4">
  <button class="btn btn-outline-success">Vote</button>
</form>

{% if success_message %}
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<div id="piechart"></div>
<script type="text/javascript">
  var poll_results = {{ poll_results|safe }};

  // Load google charts
  google.charts.load('current', { 'packages': ['corechart'] });
  google.charts.setOnLoadCallback(drawChart);

  // Draw the chart and set the chart values
  function drawChart() {
    
    poll_results.unshift(["Choice", "Vote Count"]);
    var data = google.visualization.arrayToDataTable(poll_results);

    // Optional; add a title and set the width and height of the chart
    var options = { 'width': 550, 'height': 400 };

    // Display the chart inside the <div> element with id="piechart"
    var chart = new google.visualization.PieChart(document.getElementById('piechart'));
    chart.draw(data, options);
  }
</script>

{% endif %}

{% endblock %}

_slips/slip-21/3/SimplePoll/PollApp/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Simple Poll Application</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'PollApp:home' %}">Simple Poll Application</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
        aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </nav>

  <br>

  <div class="container">
    {% block body %}
    {% endblock %}
  </div>

</body>

</html>